### ISSUE TITLE
Mod Project in RedModManager not working

### ISSUE THREAD

**Issue by dleclerc313** [ToniMacaroni/RedLoader#1]
Hello, I tried to create a mod project using RedModManager, but when I compile and run I get this error:

A project with an Output Type of Class Library cannot be started directly.
In order to debug this project, add an executable project to this solution which references the library project. Set the executable project as the startup project.

![image](https://github.com/ToniMacaroni/RedLoader/assets/72489262/15c054b3-2ca5-45e0-9109-60d602cc5a99)

I'm not sure what I need to do here to get RedLoader working.

Any help would be appreciated :)

**Comment by ToniMacaroni** [comment]
Issues with the red mod manager should be posted on the RedManger repo https://github.com/ToniMacaroni/RedManager .
As for the error make sure you open the solution (.sln) and not the poject (.csproj) file. Also starting directly from the ide is only supported for Rider for now. For setting up the same behavior with Visual Studio add the following to your csproj file

```
<PropertyGroup>
    <StartAction>Program</StartAction>
    <StartProgram>C:\Program Files %28x86%29\Steam\steam.exe</StartProgram>
    <StartArguments>-applaunch 1326470</StartArguments>
  </PropertyGroup>
  ```
  
  Make sure to adjust the steam path for `StartProgram`
