### ISSUE TITLE
New SOTF Update Red Loader No Longer Loads

### ISSUE THREAD

**Issue by dangerousroboot** [ToniMacaroni/RedLoader#11]
Red Loader all by itself, no mods, no libs or anything no longer works after the new Sons of the Forest Update.
No longer gets past 60% loading then crashes.

**Comment by ToniMacaroni** [comment]
It should still work. You can try reinstalling the game if reinstalling redloader doesn't work.

**Comment by dangerousroboot** [comment]
Reinstalled game, redloader and redloader dependencies and it still crashes.

**Comment by dangerousroboot** [comment]
Tried using RedModManager and it didn't change anything.

**Comment by ToniMacaroni** [comment]
That's strange. It works for me as well as the other modders. Perhaps you changed something about your system or an anti virus software is messing with some redloader files?

**Comment by dangerousroboot** [comment]
Well I quit the game, it updated and 5 minutes later without touching anything I tried to turn it on again and it didn't work.

**Comment by dangerousroboot** [comment]
Added the whole SOTF game folder to AV exceptions and no change.

**Comment by dangerousroboot** [comment]
![redloader](https://github.com/ToniMacaroni/RedLoader/assets/167630852/52faf9b4-c12d-40cb-b91c-02fabcd51743)
This is what it shows right before it crashes.

**Comment by dangerousroboot** [comment]
I moved the game installation folder to a different disk and it worked. idfk

**Comment by dangerousroboot** [comment]
I moved the game installation folder to a different disk and it worked. idfk
