### ISSUE TITLE
Request to contact

### ISSUE THREAD

**Issue by Wrobel1111** [ToniMacaroni/RedLoader#12]
Hello,
I know that this is very wrong use of issues tab, but after a lot of searching, this is the only way I know will work.
Dear Toni, would You be kind to email me at konarzewski32@gmail.com about Your mod to SOTF "Fancy"? I'm trying to get into modding and nagging strangers online seems to be, no matter how bad, the last way one could find any info.
Thanks (and I am closing this ticket immediately)

**Comment by ToniMacaroni** [comment]
You can get modding related help in the sons of the forest discord https://discord.gg/invite/sotf
