### ISSUE TITLE
Trojan Horse Virus in RedLoader (run on virustotal-DOT-com). NOT A FALSE POSITIVE! Pull this until cleaned of virus/s. Thanks

### ISSUE THREAD

**Issue by operator436** [ToniMacaroni/RedLoader#18]
Ran this file on virustotal.com confirmed on over 40 indie anti-virus and tools as malicious, not "a false positive" as most hackers would have you believe. They infect every gaming rig that downloads and uses this file to increase their bot strength.

I have copied other interested parties. Hacks like this concern national security among many others.

Please stop pushing that these are "false positives" and remove them or clean them. These things are soon to be a great concern and target from federal U.S. law enforcement.

**Comment by ToniMacaroni** [comment]
If you have such deep knowledge to be sure this is not a false positive point out the malicious part in the source code. Not only is the whole code uploaded here but all assemblies are not obfuscated so you are free to open them in any decompiler.
