### ISSUE TITLE
Can not save game (red loader 0.6.4)

### ISSUE THREAD

**Issue by Shinzulu** [ToniMacaroni/RedLoader#4]
Game gets stuck in save screen with grayed out back-button after trying to save.
Same with the save console command.
The save folder gets created, but no files inside.

You can get back out of the save menu by deleting a save and select "no" in the popup.

**Comment by KINGANDI360XXX** [comment]
Me Same

**Comment by Mathio95** [comment]
yea same :(

**Comment by Fulminatrix** [comment]
same

**Comment by ToniMacaroni** [comment]
I will take a look

**Comment by ParasiteDelta** [comment]
Can confirm that this issue still exists as of 0.6.5. Quite the bug, but so far this is hands-down the best modloader for the game, really impressed so far.

**Comment by Shinzulu** [comment]
Issue solved for me in 0.6.6. Thanks for your effort.

Dankeschön.

**Comment by ToniMacaroni** [comment]
Yes should be fixed in 0.6.6 . If the issue still persists feel free to reopen the issue.
