### ISSUE TITLE
Unable to save game

### ISSUE THREAD

**Issue by Snowaoffical** [ToniMacaroni/RedLoader#5]
I see there's been a fix but it still doesn't seem to work on my old and new saves. Tried to remove all mods to see if that's the problem and it wasnt. I got an error saying unable to download Il2Cpp but I ran it again and that error seemed to go away. Mods work as they should BUT when I hit the pause menu, it doesn't pause the game like it should.

**Comment by Fulminatrix** [comment]
same

**Comment by ToniMacaroni** [comment]
Should be fixed in 0.6.6 . If the issue still persists feel free to reopen the issue
