### ISSUE TITLE
Pause Menu and Heath bug

### ISSUE THREAD

**Issue by slyd3** [ToniMacaroni/RedLoader#7]
Using RedLoader 0.6.6 when i press ESC the pause menu appears but the game wont pause.
Also the health is stuck at about 10% and no meds or anything will restore it.

**Comment by Shinzulu** [comment]
Got the health-bug too, but wasn't shure, if it was a mod.
Health randomly drops to 10% after a few minutes in game. Not verified if is just a visual bug. Eating and drinking will restore the health bar until it drops again a few minutes later.

**Comment by ToniMacaroni** [comment]
Will close the issue since I can't reproduce it in the newest version (0.6.7). If the issue still persists, reopen it.
