### ISSUE TITLE
Dissapearing flask & cooking pot with insta eat

### ISSUE THREAD

**Issue by Laughincat** [ToniMacaroni/RedLoader#8]
After drinking a stew from my cooking pot in the inventory screen while the "No consume animation" was enabled, it wasn't visible in my inventory anymore as if i had no pot. However i could see it in the backpack you hold to throw stuff in a campfire. I can place it on the fire, pick it up and then hold it, but when i put it back in my inventory it's invisible again. The same thing happened to my flask after drinking clean water from it through the inventory screen.

I do not have any mods enabled. I only use the SonsGameManager config.

**Comment by ToniMacaroni** [comment]
Fixed in 0.6.8
